---
version: "1"
rules:
  - base: "main"
    upstream: "davisonio:main"
    mergeMethod: "rebase"
    assignees:
      - RogueScholar
    reviewers:
      - RogueScholar
label: ":arrow_heading_down: pull"
...
